"""CLI: batch-render all WFA result CSVs into PNG figures.

Usage:
    python scripts/render_wfa_report.py                      # render everything
    python scripts/render_wfa_report.py --filter h4          # subset by substring
    python scripts/render_wfa_report.py --in-dir research --out-dir research/figures

Output layout:
    research/figures/
      wfa_fold_results__wfa_results_h1_5_precise_rollover/
        01_fold_sharpe_bars.png
        02_is_vs_oos_scatter.png
        03_oos_metrics_panel.png
        04_param_winners.png
      h4_ensemble_daily_panel/
        01_cumulative_pnl.png
        02_drawdown.png
      ...
      INDEX.md         # auto-generated catalog

INDEX.md is the entry point — open it in any markdown viewer to browse.
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

import matplotlib.pyplot as plt

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from research.viz import chart_label, dispatch, themes  # noqa: E402
from research.viz.registry import Spec  # noqa: E402

logger = logging.getLogger("render_wfa_report")


def _slugify(stem: str) -> str:
    return stem.replace(" ", "_").replace(".", "_")


def render_one(csv_path: Path, out_dir: Path, spec: Spec) -> list[Path]:
    """Render every chart in `spec` for `csv_path`. Returns produced files."""
    df = spec.loader(csv_path)
    sub_dir = out_dir / f"{spec.name}__{csv_path.stem}"
    sub_dir.mkdir(parents=True, exist_ok=True)

    title_base = spec.title_prefix or csv_path.stem
    produced: list[Path] = []
    for i, chart_fn in enumerate(spec.chart_fns, 1):
        slug = chart_fn.__name__.replace("fig_", "")
        title = f"{title_base} — {chart_label(chart_fn)}"
        try:
            fig = chart_fn(df, title=title)
        except Exception as e:  # noqa: BLE001 — keep batch resilient
            logger.exception("Chart %s failed on %s: %s", chart_fn.__name__, csv_path.name, e)
            continue
        if fig is None:
            logger.info("Skip %s for %s (factory returned None)", chart_fn.__name__, csv_path.name)
            continue
        out_path = sub_dir / f"{i:02d}_{slug}.png"
        fig.savefig(out_path)
        plt.close(fig)
        produced.append(out_path)
        logger.info("Saved %s", out_path.relative_to(out_dir.parent))
    return produced


def write_index(out_dir: Path, produced: dict[Path, list[Path]]) -> Path:
    """Write a markdown index listing every generated figure, grouped by CSV."""
    index_path = out_dir / "INDEX.md"
    lines = ["# WFA visualization index", ""]
    lines.append(
        f"_Auto-generated by `scripts/render_wfa_report.py`. "
        f"Sources: `{out_dir.parent.name}/*.csv` ({len(produced)} files)._"
    )
    lines.append("")

    for csv_path in sorted(produced):
        figs = produced[csv_path]
        if not figs:
            continue
        lines.append(f"## `{csv_path.name}`")
        lines.append("")
        for fig_path in figs:
            rel = fig_path.relative_to(out_dir).as_posix()
            label = fig_path.stem.split("_", 1)[-1].replace("_", " ")
            lines.append(f"- **{label}** &nbsp; `{rel}`")
            lines.append(f"  ![{label}]({rel})")
        lines.append("")

    index_path.write_text("\n".join(lines), encoding="utf-8")
    return index_path


def main() -> int:
    parser = argparse.ArgumentParser(description="Render WFA result CSVs to PNG figures.")
    parser.add_argument(
        "--in-dir",
        default="research",
        type=Path,
        help="Directory to scan for *.csv (default: research)",
    )
    parser.add_argument(
        "--out-dir",
        default="research/figures",
        type=Path,
        help="Output directory for figures (default: research/figures)",
    )
    parser.add_argument(
        "--filter", default=None, help="Optional substring; only render CSVs whose name contains it"
    )
    parser.add_argument("--verbose", "-v", action="store_true", help="Debug logging")
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
    )
    themes.apply_theme()

    in_dir: Path = args.in_dir
    out_dir: Path = args.out_dir
    if not in_dir.exists():
        logger.error("Input directory does not exist: %s", in_dir)
        return 2
    out_dir.mkdir(parents=True, exist_ok=True)

    csvs = sorted(in_dir.glob("*.csv"))
    if args.filter:
        csvs = [c for c in csvs if args.filter in c.name]
    if not csvs:
        logger.warning("No CSVs matched in %s", in_dir)
        return 0

    produced: dict[Path, list[Path]] = {}
    skipped = 0
    for csv in csvs:
        spec = dispatch(csv)
        if spec is None:
            logger.info("No spec for %s — skipping", csv.name)
            skipped += 1
            continue
        produced[csv] = render_one(csv, out_dir, spec)

    index = write_index(out_dir, produced)
    total_figs = sum(len(v) for v in produced.values())
    logger.info(
        "Done. %d CSVs rendered, %d figures, %d skipped. Index: %s",
        len(produced),
        total_figs,
        skipped,
        index,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
